# Generated by cucumber-sinatra. (2015-01-02 19:01:12 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/tictactoe.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = TicTacToe

class TicTacToeWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  TicTacToeWorld.new
end
